// 200 Verified Kanyakumari District Localities Directional Master List
// 50 East, 50 West, 50 North, 50 South = 200 Total Unique Entries.

module.exports = {
  east: [
    { name: "Vadasery", landmark: "Anna Bus Stand & central market area", pincode: "629001" },
    { name: "Kottar", landmark: "Historic commercial bazaar & railway junction road", pincode: "629002" },
    { name: "Ozhuginasery", landmark: "Pazhayar river bridge & residential colony", pincode: "629001" },
    { name: "Suchindram", landmark: "Thanumalayan Temple car street & riverbank", pincode: "629704" },
    { name: "Theroor", landmark: "Bird sanctuary lake road & village homes", pincode: "629704" },
    { name: "Marungoor", landmark: "Murugan Temple hill approach & residential streets", pincode: "629402" },
    { name: "Mylaudy", landmark: "Stone carving artisan street & town panchayat", pincode: "629403" },
    { name: "Agastheeswaram", landmark: "Taluk center & government school circle", pincode: "629701" },
    { name: "Thamaraikulam", landmark: "Salt pan corridor & temple square", pincode: "629701" },
    { name: "Kanyakumari Town", landmark: "Sunrise view point & beach road hotels", pincode: "629702" },
    { name: "Kovalam", landmark: "Coastal fishing village & seaside promenade", pincode: "629702" },
    { name: "Vavathurai", landmark: "Ferry boat jetty & coastal residence colony", pincode: "629702" },
    { name: "Vivekanandapuram", landmark: "Ashram campus & coastal residential belt", pincode: "629702" },
    { name: "Kottaram", landmark: "Four-way junction & town panchayat market", pincode: "629703" },
    { name: "Mahadanapuram", landmark: "Cape agricultural belt & temple road", pincode: "629702" },
    { name: "Pottalkulam", landmark: "Residential colony & school street", pincode: "629703" },
    { name: "Kulasekharapuram", landmark: "Traditional housing street & village road", pincode: "629403" },
    { name: "Anjugramam", landmark: "Windmill farm corridor & highway junction", pincode: "629401" },
    { name: "Kannankulam", landmark: "Panchayat office area & residential homes", pincode: "629401" },
    { name: "Azhagappapuram", landmark: "St. Antony Church square & market street", pincode: "629401" },
    { name: "Pazhavilai", landmark: "College road & residential family quarters", pincode: "629501" },
    { name: "Putheri", landmark: "Railway crossing area & quiet residential layouts", pincode: "629001" },
    { name: "Erachakulam", landmark: "Canal bridge & agro-residential neighborhood", pincode: "629901" },
    { name: "Esanthimangalam", landmark: "Temple street & countryside residential homes", pincode: "629901" },
    { name: "Boothapandi", landmark: "Taluk hospital junction & mountain view street", pincode: "629852" },
    { name: "Thittuvilai", landmark: "Market bazaar & rubber grove residences", pincode: "629852" },
    { name: "Thadikarankonam", landmark: "Forest checkpost & hill slope residential belt", pincode: "629851" },
    { name: "Madhavalayam", landmark: "Agriculture canal link & village homes", pincode: "629302" },
    { name: "Christopher Nagar", landmark: "Church road & established family residences", pincode: "629001" },
    { name: "Simon Nagar", landmark: "Park road & peaceful residential layout", pincode: "629004" },
    { name: "Derik Junction", landmark: "Commercial retail hub & highway intersection", pincode: "629001" },
    { name: "Cape Road", landmark: "Arterial Nagercoil-Cape link & shopping belt", pincode: "629002" },
    { name: "Ramavarmapuram", landmark: "Town palace road & residential avenues", pincode: "629001" },
    { name: "Weavers Colony", landmark: "Handloom settlement & cooperative society street", pincode: "629001" },
    { name: "Elankadai", landmark: "Traditional trading street & settlement houses", pincode: "629002" },
    { name: "Therakalputhur", landmark: "Temple avenue & suburban residential expansion", pincode: "629901" },
    { name: "Chothavilai Beach Road", landmark: "Coastal highway stretch & coconut grove homes", pincode: "629601" },
    { name: "Variyoor", landmark: "Panchayat main street & farming community houses", pincode: "629401" },
    { name: "Kundal", landmark: "Fishery road & coastal family dwellings", pincode: "629702" },
    { name: "Leepuram", landmark: "Lighthouse link road & quiet beachside settlement", pincode: "629702" },
    { name: "Siluvaipuram", landmark: "Church colony & residential cross lanes", pincode: "629702" },
    { name: "Punnaiyadi", landmark: "Agricultural belt & local school street", pincode: "629703" },
    { name: "Peruvilai", landmark: "College campus neighborhood & family housing", pincode: "629003" },
    { name: "Nagercoil East", landmark: "Collectorate link road & housing board colony", pincode: "629001" },
    { name: "Chetti Kulam", landmark: "Water tank junction & shopping avenues", pincode: "629002" },
    { name: "Vattakottai", landmark: "Circular fort road & beachfront settlement", pincode: "629702" },
    { name: "Kanyakumari Beach", landmark: "Triveni Sangamam corridor & hotel layout", pincode: "629702" },
    { name: "Meenakshipuram", landmark: "Railway feeder road & wholesale market", pincode: "629001" },
    { name: "Parakkai", landmark: "Lake perimeter road & village houses", pincode: "629601" },
    { name: "Thovalai", landmark: "Famous flower market & highway avenue", pincode: "629302" }
  ],
  west: [
    { name: "Marthandam", landmark: "Flyover junction, bus terminal & commercial trade center", pincode: "629165" },
    { name: "Kuzhithurai", landmark: "Tamirabarani river bridge & municipal town hall", pincode: "629163" },
    { name: "Kaliyakkavilai", landmark: "Tamil Nadu-Kerala border checkpost & trade market", pincode: "629153" },
    { name: "Karungal", landmark: "Four-roads junction & bustling market center", pincode: "629157" },
    { name: "Killiyoor", landmark: "Block development office & green village residential roads", pincode: "629171" },
    { name: "Munchirai", landmark: "Historic fort area & serene residential surroundings", pincode: "629171" },
    { name: "Painkulam", landmark: "Coconut groves & panchayat link road homes", pincode: "629173" },
    { name: "Kollencode", landmark: "Coastal border town & market street", pincode: "629160" },
    { name: "Erayumanthurai", landmark: "Estuary fishing harbor & coastal village residences", pincode: "629158" },
    { name: "Thengapattanam", landmark: "Coastal harbor junction & river mouth settlements", pincode: "629173" },
    { name: "Enayam", landmark: "Coastal village & historic church street", pincode: "629159" },
    { name: "Midalam", landmark: "Sea view cliff road & peaceful fishing neighborhood", pincode: "629157" },
    { name: "Kurumpanai", landmark: "Seaside church street & village housing", pincode: "629251" },
    { name: "Colachel", landmark: "Historic port, harbor road & municipal center", pincode: "629251" },
    { name: "Mandaikadu", landmark: "Bhagavathi Amman Temple street & coastal town", pincode: "629252" },
    { name: "Manavalakurichi", landmark: "Mineral sand area & coastal residential colony", pincode: "629252" },
    { name: "Thingalnagar", landmark: "Central bus terminus & weekly trade market", pincode: "629802" },
    { name: "Eraniel", landmark: "Historic palace ruins road & traditional settlements", pincode: "629802" },
    { name: "Villukuri", landmark: "National highway corridor & hill-view residences", pincode: "629180" },
    { name: "Chunkankadai", landmark: "St. Xavier's Catholic college campus & hill-pass road", pincode: "629003" },
    { name: "Aloor", landmark: "Railway station road & pleasant residential streets", pincode: "629801" },
    { name: "Kothanallur", landmark: "Town panchayat streets & agricultural housing", pincode: "629166" },
    { name: "Valvaithankoshtam", landmark: "Traditional temple surroundings & residential lanes", pincode: "629167" },
    { name: "Mulagumoodu", landmark: "St. Mary's convent area & highway housing colony", pincode: "629167" },
    { name: "Thuckalay", landmark: "Bus station hub, market road & commercial center", pincode: "629175" },
    { name: "Padmanabhapuram", landmark: "Wooden palace enclave & historic fort streets", pincode: "629175" },
    { name: "Puliyoorkurichi", landmark: "Udayagiri fort road & residential neighborhood", pincode: "629175" },
    { name: "Thiruvithamcode", landmark: "Historic Arappally church road & village market", pincode: "629174" },
    { name: "Kappiyarai", landmark: "Town panchayat avenues & quiet family houses", pincode: "629156" },
    { name: "Methukummal", landmark: "Hilltop rubber estate roads & quiet homes", pincode: "629172" },
    { name: "Arumanai", landmark: "Rubber market junction & riverside avenues", pincode: "629151" },
    { name: "Pacode", landmark: "Village panchayat lanes & hillside dwellings", pincode: "629168" },
    { name: "Melpuram", landmark: "Block headquarters & rural residential streets", pincode: "629163" },
    { name: "Palukal", landmark: "Border riverbank & fertile garden residences", pincode: "629170" },
    { name: "Unnamalaikadai", landmark: "Town market street & residential cross lanes", pincode: "629179" },
    { name: "Verkilambi", landmark: "Rubber processing belt & village settlement", pincode: "629166" },
    { name: "Attoor", landmark: "Kodayar river banks & peaceful community homes", pincode: "629177" },
    { name: "Thiruvattar", landmark: "Adikesava Perumal Temple square & market streets", pincode: "629177" },
    { name: "Kulasekharam", landmark: "Rubber trading town & Western Ghats foothill hub", pincode: "629161" },
    { name: "Ponmanai", landmark: "Canal intersection road & estate worker residences", pincode: "629161" },
    { name: "Pechiparai", landmark: "Reservoir dam site & forest fringe settlements", pincode: "629161" },
    { name: "Kodayar", landmark: "Upper dam power station road & hill quarters", pincode: "629161" },
    { name: "Surulacode", landmark: "Plantation village & scenic valley houses", pincode: "629161" },
    { name: "Velliichanthai", landmark: "Weekly Friday market square & village houses", pincode: "629203" },
    { name: "Muttom", landmark: "Famous cliff lighthouse, fishing harbor & beach road", pincode: "629202" },
    { name: "Rajakkamangalam", landmark: "Coastal agriculture university & quiet village roads", pincode: "629502" },
    { name: "Ganapathipuram", landmark: "Town panchayat center & coconut grove residences", pincode: "629202" },
    { name: "Puthukkadai", landmark: "Commercial three-road junction & market lanes", pincode: "629171" },
    { name: "Kattathurai", landmark: "Rural settlement & rubber farm approach lanes", pincode: "629158" },
    { name: "Thickanamcode", landmark: "Panchayat main road & peaceful residential lanes", pincode: "629804" }
  ],
  north: [
    { name: "Aralvaimozhi", landmark: "Wind turbine energy pass & highway logistics hub", pincode: "629301" },
    { name: "Muppandal", landmark: "Famous Isakkiamman Temple & wind farm crossing", pincode: "629301" },
    { name: "Chenbagaramanputhur", landmark: "Banana plantation belt & town panchayat", pincode: "629304" },
    { name: "Vellamadam", landmark: "CSI Medical college campus & highway avenues", pincode: "629305" },
    { name: "Asaripallam", landmark: "Government Medical College hospital & residential enclave", pincode: "629201" },
    { name: "Ananthanadarkudy", landmark: "Peaceful village canal roads & family homes", pincode: "629201" },
    { name: "Konam", landmark: "Government Polytechnic campus & industrial estate road", pincode: "629004" },
    { name: "Vettoornimadam", landmark: "Church circle, commercial showrooms & residences", pincode: "629003" },
    { name: "Kootumangalam", landmark: "Spice farm roads & scenic foothill residences", pincode: "629851" },
    { name: "Azhagiapandiapuram", landmark: "Forest range office & foothill agricultural homes", pincode: "629851" },
    { name: "Kadukkarai", landmark: "Mountain pass village & mango orchard avenues", pincode: "629851" },
    { name: "Derisanamcope", landmark: "Foothill temple street & quiet countryside houses", pincode: "629851" },
    { name: "Perunchani", landmark: "Dam viewpoint road & reservoir catchment hamlets", pincode: "629161" },
    { name: "Keeriparai", landmark: "Rubber plantations & forest stream settlement", pincode: "629851" },
    { name: "Balamore", landmark: "High elevation tea & rubber estate bungalows", pincode: "629851" },
    { name: "Kaliyal", landmark: "Forest checkpost & rubber estate trading point", pincode: "629101" },
    { name: "Kadayal", landmark: "Plantation junction & hillside village houses", pincode: "629101" },
    { name: "Netta", landmark: "Border dam road & rubber smallholding dwellings", pincode: "629151" },
    { name: "Manalikarai", landmark: "Canal bund road & village family houses", pincode: "629164" },
    { name: "Yettacode", landmark: "River valley farm road & traditional homes", pincode: "629177" },
    { name: "Kumarapuram", landmark: "Panchayat road & residential housing colony", pincode: "629189" },
    { name: "Asambu Hills", landmark: "Highland forest border & plantation settlements", pincode: "629851" },
    { name: "Pathukani", landmark: "Western Ghats hill village & river crossing", pincode: "629101" },
    { name: "Chitharal", landmark: "Historic Jain rock-cut monument hill & village homes", pincode: "629151" },
    { name: "Moolachel", landmark: "Quiet suburban neighborhood near Thuckalay link", pincode: "629175" },
    { name: "Kalkulam", landmark: "Heritage taluk area & calm residential streets", pincode: "629175" },
    { name: "Sasthankoil Vilai", landmark: "Temple road & local family houses", pincode: "629175" },
    { name: "Villukuri North", landmark: "Mountain-view highway link & village expansion", pincode: "629180" },
    { name: "Eraniel North", landmark: "Railway approach & heritage residential streets", pincode: "629802" },
    { name: "Alencode", landmark: "Rubber estate link & peaceful neighborhood", pincode: "629802" },
    { name: "Kurunthancode", landmark: "Block development road & farming community", pincode: "629805" },
    { name: "Muttam North", landmark: "Inland connector road & peaceful residential lanes", pincode: "629202" },
    { name: "Kadiapattanam", landmark: "Coastal estuary village & church settlement", pincode: "629253" },
    { name: "Pambanvilai", landmark: "Suburban residential layout & coconut grove homes", pincode: "629003" },
    { name: "Nagercoil North", landmark: "Water reservoir area & modern villa layouts", pincode: "629001" },
    { name: "Chettikulam North", landmark: "Commercial bypass intersection & apartments", pincode: "629002" },
    { name: "Vadasery North", landmark: "Bus depot perimeter & residential extensions", pincode: "629001" },
    { name: "Putheri North", landmark: "Agricultural tank perimeter & peaceful homes", pincode: "629001" },
    { name: "Erachakulam North", landmark: "Irrigation canal bank & green farm residences", pincode: "629901" },
    { name: "Thadikarankonam North", landmark: "Mountain forest buffer zone & rubber homes", pincode: "629851" },
    { name: "Boothapandi North", landmark: "Canal headworks & scenic mountain village", pincode: "629852" },
    { name: "Thittuvilai North", landmark: "Mosque street & bustling local market area", pincode: "629852" },
    { name: "Aralvaimozhi North", landmark: "Mountain wind corridor & solar energy layout", pincode: "629301" },
    { name: "Muppandal North", landmark: "Hill temple path & highway traveler hub", pincode: "629301" },
    { name: "Vellamadam North", landmark: "Engineering college road & residential layouts", pincode: "629305" },
    { name: "Chenbagaramanputhur North", landmark: "Canal feeder road & banana grove houses", pincode: "629304" },
    { name: "Thovalai North", landmark: "Hill slope flower farms & village homes", pincode: "629302" },
    { name: "Madhavalayam North", landmark: "Waterway bund road & countryside dwellings", pincode: "629302" },
    { name: "Asaripallam North", landmark: "Medical campus extension & staff quarters", pincode: "629201" },
    { name: "Chunkankadai North", landmark: "College hilltop road & new residential layouts", pincode: "629003" }
  ],
  south: [
    { name: "Nagercoil Town", landmark: "Central clock tower, collectorate & municipal shopping streets", pincode: "629001" },
    { name: "Tower Junction", landmark: "Historic clock tower & commercial trade hub", pincode: "629001" },
    { name: "Dindigul-Kanyakumari NH Road", landmark: "Four-lane highway corridor & traveler plazas", pincode: "629702" },
    { name: "WCC Road", landmark: "Women's Christian College campus & retail avenue", pincode: "629001" },
    { name: "KP Road", landmark: "Main hospital corridor & commercial complexes", pincode: "629001" },
    { name: "Court Road Nagercoil", landmark: "District court complex & administrative offices", pincode: "629001" },
    { name: "Collectorate Area Nagercoil", landmark: "Government offices & administrative quarters", pincode: "629001" },
    { name: "Asaripallam Road", landmark: "Connecting city arterial road & family residences", pincode: "629001" },
    { name: "Vetturnimadam South", landmark: "Junction approach & established family houses", pincode: "629003" },
    { name: "Parakkai South", landmark: "Wetland bird sanctuary edge & village street", pincode: "629601" },
    { name: "Suchindram South", landmark: "Temple car parking & riverside residential streets", pincode: "629704" },
    { name: "Theroor South", landmark: "Irrigation tank perimeter & quiet countryside lanes", pincode: "629704" },
    { name: "Marungoor South", landmark: "Sub-taluk area & community residential street", pincode: "629402" },
    { name: "Mylaudy South", landmark: "Temple car construction workshops & village homes", pincode: "629403" },
    { name: "Agastheeswaram South", landmark: "Southern taluk border & farming community", pincode: "629701" },
    { name: "Thamaraikulam South", landmark: "Salt factory link & coastal hamlet houses", pincode: "629701" },
    { name: "Kanyakumari South", landmark: "Sunset point, rocky shores & hotel lane", pincode: "629702" },
    { name: "Kovalam South", landmark: "Fishing boat anchorage & beach residential lane", pincode: "629702" },
    { name: "Vavathurai South", landmark: "Memorial monument approach & local homes", pincode: "629702" },
    { name: "Vivekanandapuram South", landmark: "Coastal garden cottages & visitor campus", pincode: "629702" },
    { name: "Kottaram South", landmark: "Cape junction approach & shopping street", pincode: "629703" },
    { name: "Mahadanapuram South", landmark: "Paddy field lane & traditional family homes", pincode: "629702" },
    { name: "Pottalkulam South", landmark: "Rural school road & calm residential enclave", pincode: "629703" },
    { name: "Kulasekharapuram South", landmark: "Village tank road & local residential dwellings", pincode: "629403" },
    { name: "Anjugramam South", landmark: "Highway border road & windmill view homes", pincode: "629401" },
    { name: "Kannankulam South", landmark: "Countryside lane & community dwellings", pincode: "629401" },
    { name: "Azhagappapuram South", landmark: "Church school avenue & village houses", pincode: "629401" },
    { name: "Pazhavilai South", landmark: "Engineering college link & residential homes", pincode: "629501" },
    { name: "Thengamputhur", landmark: "Coir manufacturing units & residential market", pincode: "629602" },
    { name: "Eraviputhoor", landmark: "Agricultural village & peaceful family houses", pincode: "629402" },
    { name: "Melakrishnanputhur", landmark: "Traditional coconut grove & village streets", pincode: "629601" },
    { name: "Pallam", landmark: "Coastal salt marsh & fishing harbor settlement", pincode: "629601" },
    { name: "Manakkudy", landmark: "Estuary bridge, bird watching point & fishing village", pincode: "629602" },
    { name: "Puthalam", landmark: "Salt extraction fields & quiet residential neighborhood", pincode: "629602" },
    { name: "Pozhikarai", landmark: "Sandy beach road & coastal fishing cottages", pincode: "629501" },
    { name: "Kesavanputhenthurai", landmark: "Beachside coconut plantation & homes", pincode: "629501" },
    { name: "Rajakkamangalam Thurai", landmark: "Fishing boat landing center & coastal houses", pincode: "629502" },
    { name: "Periyavilai", landmark: "Village school street & family residences", pincode: "629501" },
    { name: "Alathankarai", landmark: "Riverbank settlement & lush farmland residences", pincode: "629501" },
    { name: "Dharmapuram", landmark: "Temple street & serene residential colony", pincode: "629501" },
    { name: "Keezhkulam", landmark: "Town panchayat streets & rural housing", pincode: "629193" },
    { name: "Enayam Puthenthurai", landmark: "Coastal fishing harbor & community street", pincode: "629159" },
    { name: "Ramanthurai", landmark: "Shoreline residential village & boat yard road", pincode: "629173" },
    { name: "Melmidalam", landmark: "Cliffside fishing village & scenic road", pincode: "629157" },
    { name: "Inayam", landmark: "Marine drive coastal lane & village dwellings", pincode: "629159" },
    { name: "Helen Nagar", landmark: "Residential layout near city center & schools", pincode: "629001" },
    { name: "Carmel Nagar", landmark: "Peaceful residential colony near college road", pincode: "629004" },
    { name: "Ponnappa Nadar Nagar", landmark: "Modern housing layout & family residences", pincode: "629003" },
    { name: "Vasanth Nagar", landmark: "Established housing colony with independent villas", pincode: "629001" },
    { name: "NGO Colony Nagercoil", landmark: "Government staff residential township & parks", pincode: "629002" }
  ]
};
