// Master list of 30 washing machine brands for Karur
module.exports = [
  { id: 1, name: "Samsung", slug: "samsung-washing-machine-repair-service-in-karur.html" },
  { id: 2, name: "Whirlpool", slug: "whirlpool-washing-machine-repair-service-in-karur.html" },
  { id: 3, name: "Bosch", slug: "bosch-washing-machine-repair-service-in-karur.html" },
  { id: 4, name: "IFB", slug: "ifb-washing-machine-repair-service-in-karur.html" },
  { id: 5, name: "Haier", slug: "haier-washing-machine-repair-service-in-karur.html" },
  { id: 6, name: "Videocon", slug: "videocon-washing-machine-repair-service-in-karur.html" },
  { id: 7, name: "Godrej", slug: "godrej-washing-machine-repair-service-in-karur.html" },
  { id: 8, name: "Panasonic", slug: "panasonic-washing-machine-repair-service-in-karur.html" },
  { id: 9, name: "Onida", slug: "onida-washing-machine-repair-service-in-karur.html" },
  { id: 10, name: "Hitachi", slug: "hitachi-washing-machine-repair-service-in-karur.html" },
  { id: 11, name: "Midea", slug: "midea-washing-machine-repair-service-in-karur.html" },
  { id: 12, name: "Siemens", slug: "siemens-washing-machine-repair-service-in-karur.html" },
  { id: 13, name: "Toshiba", slug: "toshiba-washing-machine-repair-service-in-karur.html" },
  { id: 14, name: "Daewoo", slug: "daewoo-washing-machine-repair-service-in-karur.html" },
  { id: 15, name: "Intex", slug: "intex-washing-machine-repair-service-in-karur.html" },
  { id: 16, name: "Kelvinator", slug: "kelvinator-washing-machine-repair-service-in-karur.html" },
  { id: 17, name: "Kenstar", slug: "kenstar-washing-machine-repair-service-in-karur.html" },
  { id: 18, name: "Sharp", slug: "sharp-washing-machine-repair-service-in-karur.html" },
  { id: 19, name: "Voltas", slug: "voltas-washing-machine-repair-service-in-karur.html" },
  { id: 20, name: "Lloyd", slug: "lloyd-washing-machine-repair-service-in-karur.html" },
  { id: 21, name: "BPL", slug: "bpl-washing-machine-repair-service-in-karur.html" },
  { id: 22, name: "Voltas Beko", slug: "voltas-beko-washing-machine-repair-service-in-karur.html" },
  { id: 23, name: "Thomson", slug: "thomson-washing-machine-repair-service-in-karur.html" },
  { id: 24, name: "Motorola", slug: "motorola-washing-machine-repair-service-in-karur.html" },
  { id: 25, name: "VW", slug: "vw-washing-machine-repair-service-in-karur.html" },
  { id: 26, name: "Electrolux", slug: "electrolux-washing-machine-repair-service-in-karur.html" },
  { id: 27, name: "TCL", slug: "tcl-washing-machine-repair-service-in-karur.html" },
  { id: 28, name: "White Westinghouse", slug: "white-westinghouse-washing-machine-repair-service-in-karur.html" },
  { id: 29, name: "Havells", slug: "havells-washing-machine-repair-service-in-karur.html" },
  { id: 30, name: "Acer", slug: "acer-washing-machine-repair-service-in-karur.html" }
];
